### ISSUE TITLE
Improvements and fixes from intexsys.lv

### ISSUE THREAD

**Issue by oleg-andreyev** [schmittjoh/twig.js#96]
Disclaimer: This is parent issue for all fixes/improvements we had made and to trace progress
- [x] #97 - adding "SIMPLE" mode to compile_dev.js for more developer friendly view
- [x] #98 avoid creating GLOBAL variable and exposing it, created `twig.templates` namespace (fixes #92)
- [x] #100 fixing namespace of Twig classes ( ! ) not all
- [x] #99 fixing MacroCompiler - context did not contain current arguments
- [ ] Tests

To revisit:
- [ ] fixing issue when including template from variable
